### ISSUE TITLE
[PE-D][Tester D] User Guide Title is Still AB-3

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-W10-3/tp#104]
ScreenShot:

![Screenshot 2024-04-05 at 4.05.04 PM.png](https://raw.githubusercontent.com/linnn-7/ped/main/files/f2221470-d21c-404a-804b-fc5a2f85616d.png)

Maybe should change this title to Pedagogue Pages.

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: linnn-7/ped#1

**Comment by J-wang-CSMA** [comment]
Fixed
