### ISSUE TITLE
[PE-D][Tester A] add command bug for name parameter

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-W10-3/tp#105]
![image.png](https://raw.githubusercontent.com/Jolonauh/ped/main/files/37a1ac6b-bc78-4f21-b89d-d7a138170976.png)

Attempting to add a student with the name "David Li123" results in the display box displaying "This person already exists in the contact list." I expect the behaviour to give an error regarding the invalid name instead.

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: Jolonauh/ped#1

**Comment by ongzhili** [comment]
Related to #122 

Category: Won't Fix / Invalid

**Comment by ongzhili** [comment]
Closed
