### ISSUE TITLE
[PE-D][Tester A] add command bug in name parameter

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-W10-3/tp#110]
![image.png](https://raw.githubusercontent.com/Jolonauh/ped/main/files/92ccf088-23f7-4922-b426-de07f11b861c.png)

Using "test2" for the name parameter allows a student to be added even though the name contains numeric values.

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: Jolonauh/ped#3

**Comment by ongzhili** [comment]
Duplicate of #108 

Category: Must Fix (Mention in UG about capitalization)
