### ISSUE TITLE
[PE-D][Tester D] Sort by Names When Names are Numbers

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-W10-3/tp#128]
Since your application allows names to be pure numbers, when utilising your application, it's worth noting that if I execute the command "sort /name," it will arrange all the numbers at the beginning, which might not be aesthetically pleasing.

Command: sort /name

Suggestions: Maybe should limit users from employing numbers as names, and when sorting by names, only alphabetical names should be taken into account.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: linnn-7/ped#7

**Comment by ongzhili** [comment]
Category: Not allowed to fix in 1.4

Instead, disclaimer in 'Known issues' will be added.
